# template:
#   - sensor:
#       - name: "lichtintensiteit gemiddeld"
#         unique_id: lichtintensiteit_gemiddeld
#         state_class: measurement
#         device_class: irradiance
#         icon: mdi:calculator
#         state: >
#           {% if is_state('sun.sun', 'above_horizon') %}
#             {% set s1 = states('sensor.thuis_globale_stralingsintensiteit') | float(none) %}
#             {% set s2 = states('sensor.buienradar_irradiance') | float(none) %}
#             {% if s1 is not none and s2 is not none %}
#               {{ ((s1 + s2) / 2) | round(1) }}
#             {% else %}
#               0
#             {% endif %}
#           {% else %}
#             0
#           {% endif %}





sensor:
  - platform: min_max
    name: Buitentemperatuur gemiddeld
    unique_id: buitentemperatuur_gemiddeld
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.thuis_temperatuur
      - sensor.adlar_ambient_temp_t1
      - sensor.ducobox_buitentemperatuur
      - sensor.buienradar_temperature

  - platform: min_max
    name: Buitenluchtvochtigheid gemiddeld
    unique_id: buitenluchtvochtigheid_gemiddeld
    type: mean
    round_digits: 0
    entity_ids:
      - sensor.thuis_luchtvochtigheid
      - sensor.buienradar_humidity




  - platform: min_max
    name: Buitenluchtdruk gemiddeld
    unique_id: buitenluchtdruk_gemiddeld
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.thuis_luchtdruk
      - sensor.buienradar_pressure





  - platform: min_max
    name: lichtintensiteit gemiddeld
    unique_id: lichtintensiteit_gemiddeld
    type: mean
    round_digits: 1
    entity_ids:
    #  - sensor.thuis_globale_stralingsintensiteit
      - sensor.buienradar_irradiance


  - platform: min_max
    name: Kamertemperatuur gemiddeld
    unique_id: kamertemperatuur_gemiddeld
    type: mean
    round_digits: 1
    entity_ids:
#      - sensor.ducobox_temperatuur_woonkamer
      - sensor.woonkamer_temperature_2
      - sensor.woonkamer_temperature
