#
# Loads default set of integrations. Do not remove.
#
default_config:

homeassistant:
  packages: !include_dir_named packages

  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 127.0.0.1
        - ::1

  customize_glob:
    "number.adlar_*": # For number entities from integrations
      mode: box

#
# Text to speech
#
tts:
  platform: google_translate

#
# SQLite: database zonder history: tot purge datum
#
recorder:
  #  db_url: !secret mariadb_url
  purge_keep_days: 7
  commit_interval: 5
  auto_purge: true
  auto_repack: true
  exclude:
    entity_globs:
      - sensor.time*
      - sensor.date*
    entities:
      - sensor.huidige_elektriciteitsprijs_all_in
      - sensor.average_electricity_price
    #   - sensor.date_and_time
    #   - sensor.date_time
    #   - sensor.date_time_iso
    #    entities:
    #      - sensor.watermeter_totaal_water_verbruik_cost
    #      - sensor.ha_uptime_minutes
    #    entity_globs:
    #      - sensor.*uptime
    domains:
      - automation
      - update
      - media_player

#
# InfluxDB: database met history: lange termijn data
#
influxdb:
  default_measurement: state
  include:
    entity_globs:
      - sensor.smartmeter_*
      #      - sensor.envoy_lifetime_*
      - sensor.envoy_122025007960_*
      #      - sensor.adlar_warmtepomp_*
      - sensor.adlar*
      - sensor.zonnepanelen_*
      - sensor.wp_*
      - sensor.vermogen_per_wp_*
      - sensor.watermeter_*
      - sensor.airq_*_air_temperature
      - sensor.airq_*_humidity
      - sensor.airq_*_carbon_dioxide_co2_level
      - sensor.*_last_seen
      - sensor.warmtepomp_energieverbruik_e_*
      - sensor.degree_days_this_year
      - sensor.weighted_degree_days_this_year
      - sensor.energy_consumption_*
    entities:
      - sensor.volle_zonuren
#  exclude:
#    entity_globs:
#      - adlar_warmtepomp_wp_* # local tuya

#
# Files include
#
script: !include scripts.yaml #ja
scene: !include scenes.yaml #ja
group: !include group.yaml
climate: !include climate.yaml

# My own handmade automations
automation manual: !include_dir_list automation/
# Automations I create in the UI
automation ui: !include automations.yaml #ja

#
# Directories include
#
#template: !include_dir_merge_list templates/

#`
# Log data
#
logger:
  default: warning
  filters:
    homeassistant.components.script:
      - "Timeout when calling resource"
    custom_components.dual_smart_thermostat.hvac_device.generic_hvac_device:
      # Door de zin hier af te breken, filtert hij zowel de 'verwarmen' als 'koelen' varianter eruit
      - "The climate mode is OFF, but the switch device is ON"
  # logs:
  #   homeassistant.components.automation: debug





#  logs:
#    rest_command: debug
#    homeassistant.components.rest.util: error

logbook:
  exclude:
    entities:
      - sensor.warmtepomp_meter_last_seen
    entity_globs:
      - sensor.envoy_*_inverter_*
      - sensor.inverter_*
      - sensor.time*
      - sensor.date*
      - sensor.*_last_seen
    domains:
      - Envoy-S-Metered-EU
      - Forecast.Solar
      #      - time_date
      #      - date_time
      - Uptime
      - OpenTherm

#shell_command:
#  run_remote_db_backup: !secret mariadb_backup

# device_tracker:
# - platform: ddwrt
#   host: 192.168.1.2
#   username: admin
#   password: Ell82saS!@

frontend:
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js?hacstag=190927524421
    - /hacsfiles/sidebar-organizer/sidebar-organizer.js?hacstag=932534411420


# climate:
#   - platform: dual_smart_thermostat
#     name: WP thermostaat
#     heater: switch.hvac_verwarmen # <-required
#     cooler: switch.hvac_koelen # <-required
#     #    heat_pump_cooling: switch.hvac_koelen
#     target_sensor: sensor.smart_thermostat_x_temperatuur
#     min_temp: 10
#     max_temp: 25
#     keep_alive:
#       minutes: 1
#     heat_cool_mode: true


