#
# Loads default set of integrations. Do not remove.
#
default_config:

homeassistant:

  packages: !include_dir_named packages

  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 127.0.0.1
        - ::1

  customize_glob:
    "number.adlar_*": # For number entities from integrations
      mode: box

# voor persons https://companion.home-assistant.io/docs/getting_started/
# cloud:

#
# Http setup
#
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.0/24
    - 127.0.0.1
    - ::1

#
# Text to speech
#
tts:
  platform: google_translate

#
# SQLite: database zonder history: tot purge datum
#
recorder:
#  db_url: !secret mariadb_url
  purge_keep_days: 7
  commit_interval: 5
  auto_purge: true
  auto_repack: true
  exclude:
    entity_globs:
      - sensor.time*
      - sensor.date*
    # entities:
    #   - sensor.date_and_time
    #   - sensor.date_time
    #   - sensor.date_time_iso
    #    entities:
    #      - sensor.watermeter_totaal_water_verbruik_cost
    #      - sensor.ha_uptime_minutes
    #    entity_globs:
    #      - sensor.*uptime
    domains:
      - automation
      - update
      - media_player

      

#
# InfluxDB: database met history: lange termijn data
#
influxdb:
  default_measurement: state
  include:
    entity_globs:
      - sensor.smartmeter_*
#      - sensor.envoy_lifetime_*
      - sensor.envoy_122025007960_*
#      - sensor.adlar_warmtepomp_*
      - sensor.adlar*
      - sensor.zonnepanelen_*
      - sensor.wp_*
      - sensor.vermogen_per_wp_*
      - sensor.watermeter_*
      - sensor.airq_*_air_temperature
      - sensor.airq_*_humidity
      - sensor.airq_*_carbon_dioxide_co2_level
    entities:
      - sensor.volle_zonuren
  exclude:
    entity_globs:
      - adlar_warmtepomp_wp_*  # local tuya



#
# Files include
#
script: !include scripts.yaml
scene: !include scenes.yaml
group: !include group.yaml

# My own handmade automations
automation manual: !include_dir_list automation/
# Automations I create in the UI
automation ui: !include automations.yaml

#
# Directories include
#
template: !include_dir_merge_list templates/

#`
# Log data
#
logger:
  default: warning # critical fatal error warning(=default) warn info debug notset
  filters: # filter out
    homeassistant.components.script:
      - 'Timeout when calling resource "http://192.168.1.73/*"'
#  logs:
#    rest_command: debug
#    homeassistant.components.rest.util: error

logbook:
  exclude:
    entities:
      - sensor.warmtepomp_meter_last_seen
    entity_globs:
      - sensor.envoy_*_inverter_*
      - sensor.inverter_*
      - sensor.time*
      - sensor.date*
    domains:
      - Envoy-S-Metered-EU
      - Forecast.Solar
#      - time_date
#      - date_time
      - Uptime
      - OpenTherm

#shell_command:
#  run_remote_db_backup: !secret mariadb_backup


# device_tracker:
# - platform: ddwrt
#   host: 192.168.1.2
#   username: admin
#   password: Ell82saS!@

frontend:
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js?hacstag=190927524421
    - /hacsfiles/sidebar-organizer/sidebar-organizer.js?hacstag=932534411420
#    - /hacsfiles/sidebar-organizer/sidebar-organizer.js?hacstag=932534411400
#    - /hacsfiles/sidebar-organizer/sidebar-organizer.js?hacstag=932534411341



# climate:
#   - platform: generic_thermostat 
#     name: WP thermostaat
#     heater: switch.adlar_main_switch
#     target_sensor: sensor.woonkamer_temperature
#     target_temp_step: 0.5
#     precision: 0.1
#     min_temp: 15
#     max_temp: 23  932534411400
#     ac_mode: false
#     initial_hvac_mode: "off" 
climate:
  - platform: dual_smart_thermostat
    name: WP thermostaat
    heater: switch.hvac_verwarmen # <-required
    cooler: switch.hvac_koelen # <-required
#    heat_pump_cooling: switch.hvac_koelen
    heat_cool_mode: false # <-- or not set
    target_sensor: sensor.smart_thermostat_x_temperatuur
#    heat_cool_mode: true # <-required
#    initial_hvac_mode: "heat"
    min_temp: 10
    max_temp: 25
    # target_temp_low: 19.5
    # target_temp_high: 19.5
    keep_alive:
      minutes: 1

# sensor:
#   - platform: min_max
#     name: Buitentemperatuur gemiddeld
#     unique_id: buitentemperatuur_gemiddeld
#     type: mean
#     entity_ids:
#         - sensor.thuis_temperatuur
#         - sensor.adlar_ambient_temp_t1
#         - sensor.ducobox_temperatuur_toevoer_van_buiten

# #      - sensor.buienradar_temperature