alias: "WP AV: temp set door woonkamer temperatuur"
id: "wp_av_temp_set_door_woonkamer_temperatuur"
description: ""
triggers:
  - trigger: state
    entity_id:
      - climate.smart_thermostat_x
    attribute: current_temperature
    for:
      hours: 0
      minutes: 0
      seconds: 1
  - trigger: time_pattern
    minutes: /30
conditions:
  - condition: device
    type: is_on
    device_id: 8fe73d3f492bff3665c627a0366203e1
    entity_id: 5b4cd23b8f07ee081f84f496ae2b4673
    domain: switch
  - condition: state
    entity_id: binary_sensor.adlar_warmtepomp_wp_defrosting
    state:
      - "off"
    for:
      hours: 0
      minutes: 15
      seconds: 0
  - condition: state
    entity_id: input_select.wp_selecteer_bedrijfsmodus
    state: Auto verwarmen
    enabled: true
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: sensor.kamertemperatuur_waardering
            state:
              - Te koud
            for:
              hours: 0
              minutes: 15
              seconds: 0
          - condition: or
            conditions:
              - condition: state
                entity_id: sensor.kamertemperatuur_verandering
                state:
                  - Daalt
                for:
                  hours: 0
                  minutes: 2
                  seconds: 0
                enabled: true
              - condition: state
                entity_id: sensor.kamertemperatuur_verandering
                state:
                  - Stabiel
                for:
                  hours: 0
                  minutes: 30
                  seconds: 0
                enabled: true
          - condition: not
            conditions:
              - condition: state
                entity_id: sensor.kamertemperatuur_verandering
                state:
                  - Stijgt
                for:
                  hours: 0
                  minutes: 5
                  seconds: 0
            enabled: false
          - condition: numeric_state
            entity_id: number.adlar_warmtepomp_wp_temp_set
            above: sensor.adlar_warmtepomp_wp_inlet_temp
            value_template: "{{state.state | float -2}}"
            alias: Temp set is 3 graden meer dan inlet temp
            enabled: false
          - condition: state
            entity_id: timer.wachttijd_temp_set_veranderen
            state: idle
          - condition: state
            entity_id: binary_sensor.adlar_warmtepomp_maintenance
            state:
              - "off"
            for:
              hours: 0
              minutes: 0
              seconds: 0
          - condition: state
            entity_id: binary_sensor.adlar_warmtepomp_wp_defrosting
            state:
              - "off"
            for:
              hours: 0
              minutes: 30
              seconds: 0
        sequence:
          - if:
              - condition: device
                device_id: 8fe73d3f492bff3665c627a0366203e1
                domain: select
                entity_id: 7f38202ef83365cd00a43a72844d6a23
                type: selected_option
                option: Eco
            then:
              - action: number.set_value
                metadata: {}
                data:
                  value: >
                    {% set hysterese_p26 = 2 %}

                    {% set inlet_temp =
                    states('sensor.adlar_warmtepomp_wp_inlet_temp') | float %}

                    {% set max_set_temp = (inlet_temp + hysterese_p26 + 1)  |
                    int %}

                    {% set current_temp_set =
                    states('number.adlar_warmtepomp_wp_temp_set') | float %}

                    {{ [current_temp_set + 1, max_set_temp] | min }}
                target:
                  entity_id: number.adlar_warmtepomp_wp_temp_set
                enabled: true
              - action: timer.start
                metadata: {}
                data:
                  duration: 00:{{ states('input_number.temperatuurvertraging') | int }}
                target:
                  entity_id: timer.wachttijd_temp_set_veranderen
              - action: logbook.log
                metadata: {}
                data:
                  entity_id: number.adlar_warmtepomp_wp_temp_set
                  name: Adlar automation
                  message: >-
                    WP Auto Verwarmen: temp set temperatuur regeling door
                    woonkamer temperatuur: eco mode temp set
            else:
              - action: number.set_value
                metadata: {}
                data:
                  value: >
                    {% set max_set_temp = 50 %}

                    {% set current_temp_set =
                    states('number.adlar_warmtepomp_wp_temp_set') | float %}

                    {% set opt_temp_set =
                    states('input_number.wp_berekende_optimale_temp_set') | int
                    %}

                    {{ [current_temp_set + 1, max_set_temp] | min }}
                target:
                  entity_id: number.adlar_warmtepomp_wp_temp_set
                enabled: true
              - action: timer.start
                metadata: {}
                data:
                  duration: 00:{{ states('input_number.temperatuurvertraging') | int }}
                target:
                  entity_id: timer.wachttijd_temp_set_veranderen
              - action: logbook.log
                metadata: {}
                data:
                  entity_id: number.adlar_warmtepomp_wp_temp_set
                  name: Adlar automation
                  message: >-
                    WP Auto Verwarmen: temp set temperatuur regeling door
                    woonkamer temperatuur: temp set + 1
        alias: >-
          Temp set 1 graad verhogen bij te koud en niet stijgende
          kamertemperatuur
      - conditions:
          - condition: state
            entity_id: binary_sensor.adlar_warmtepomp_wp_defrosting
            state:
              - "off"
            for:
              hours: 0
              minutes: 30
              seconds: 0
          - condition: state
            entity_id: binary_sensor.wp_compressor
            state:
              - "on"
          - condition: state
            entity_id: binary_sensor.adlar_warmtepomp_maintenance
            state:
              - "off"
            enabled: true
            for:
              hours: 0
              minutes: 0
              seconds: 0
          - condition: state
            entity_id: sensor.kamertemperatuur_waardering
            state: Te warm
            enabled: true
            for:
              hours: 0
              minutes: 1
              seconds: 0
          - condition: not
            conditions:
              - condition: state
                entity_id: sensor.kamertemperatuur_verandering
                state: Daalt
                for:
                  hours: 0
                  minutes: 1
                  seconds: 0
          - condition: state
            entity_id: timer.wachttijd_temp_set_veranderen
            state: idle
        sequence:
          - action: number.set_value
            metadata: {}
            data:
              value: >
                {% set current_temp_set =
                states('number.adlar_warmtepomp_wp_temp_set') | float %} 

                {% set opt_temp_set =
                states('input_number.wp_berekende_optimale_temp_set') | int %}

                {% set inlet_temp =
                states('sensor.adlar_warmtepomp_wp_inlet_temp') | float %} 

                {{ current_temp_set - 1 }}
            target:
              entity_id: number.adlar_warmtepomp_wp_temp_set
            enabled: true
          - action: timer.start
            metadata: {}
            data:
              duration: 00:{{ states('input_number.temperatuurvertraging') | int }}
            target:
              entity_id: timer.wachttijd_temp_set_veranderen
          - action: logbook.log
            metadata: {}
            data:
              entity_id: number.adlar_warmtepomp_wp_temp_set
              name: Adlar automation
              message: >-
                WP Auto Verwarmen: temp set temperatuur regeling door woonkamer
                temperatuur: temp set - 1
        alias: >-
          Temp set 1 graad verlagen bij te warm, stijgende kamertemperatuur en
          compressor actief
mode: single
