alias: "WP AV: stel in de optimale en temp set temperatuur"
description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.wp_compressor
    to: "off"
    from: "on"
    for:
      hours: 0
      minutes: 0
      seconds: 0
    id: Compressor stopt
    enabled: true
  - trigger: state
    entity_id:
      - binary_sensor.wp_compressor
    to: "on"
    from: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 0
    id: Compressor start
    enabled: true
conditions:
  - condition: device
    type: is_on
    device_id: 8fe73d3f492bff3665c627a0366203e1
    entity_id: 5b4cd23b8f07ee081f84f496ae2b4673
    domain: switch
  - condition: state
    entity_id: input_select.wp_selecteer_bedrijfsmodus
    state: Auto verwarmen
    enabled: true
  - condition: state
    entity_id: binary_sensor.adlar_warmtepomp_wp_defrosting
    state: "off"
  - condition: state
    entity_id: binary_sensor.adlar_warmtepomp_maintenance
    state:
      - "off"
  - condition: numeric_state
    entity_id: climate.smart_thermostat_x
    attribute: temperature
    above: 20
  - condition: state
    entity_id: select.adlar_warmtepomp_wp_working_mode
    state:
      - Normaal
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Compressor stopt
        sequence:
          - if:
              - condition: state
                entity_id: sensor.kamertemperatuur_waardering
                state: Te koud
            then:
              - action: input_number.set_value
                metadata: {}
                data:
                  value: >
                    {% set current_temp_set =
                    states('number.adlar_warmtepomp_wp_temp_set') | float %}

                    {% set inlet_temp =
                    states('sensor.adlar_warmtepomp_wp_inlet_temp') | float %}

                    {{ current_temp_set + 1 }}
                target:
                  entity_id: input_number.wp_berekende_optimale_temp_set
              - if:
                  - condition: state
                    entity_id: timer.wachttijd_temp_set_veranderen
                    state:
                      - idle
                then:
                  - action: number.set_value
                    metadata: {}
                    data:
                      value: >
                        {% set opt_temp_set =
                        states('input_number.wp_berekende_optimale_temp_set') |
                        int %}

                        {{ opt_temp_set }}
                    target:
                      entity_id: number.adlar_warmtepomp_wp_temp_set
                    enabled: true
              - action: logbook.log
                metadata: {}
                data:
                  entity_id: number.adlar_warmtepomp_wp_temp_set
                  name: Adlar automation
                  message: >-
                    WP Auto Verwarmen: stel in de optimale en de temp set
                    temperatuur: optie 1, temp set + 1
              - action: timer.start
                metadata: {}
                data:
                  duration: 00:{{ states('input_number.temperatuurvertraging') | int }}
                target:
                  entity_id: timer.wachttijd_temp_set_veranderen
            else:
              - if:
                  - condition: state
                    entity_id: sensor.kamertemperatuur_waardering
                    state: Te warm
                    for:
                      hours: 0
                      minutes: 10
                      seconds: 0
                  - condition: state
                    entity_id: sensor.kamertemperatuur_verandering
                    for:
                      hours: 0
                      minutes: 10
                      seconds: 0
                    state: Stijgt
                then:
                  - action: input_number.set_value
                    metadata: {}
                    data:
                      value: >
                        {% set temp_set =
                        states('number.adlar_warmtepomp_wp_temp_set') | float %}

                        {% set inlet_temp =
                        states('sensor.adlar_warmtepomp_wp_inlet_temp') | float
                        %}

                        {{ [([temp_set - 1, inlet_temp - 1]  | min), 24] |max }}
                    target:
                      entity_id: input_number.wp_berekende_optimale_temp_set
                    enabled: true
                  - if:
                      - condition: state
                        entity_id: timer.wachttijd_temp_set_veranderen
                        state:
                          - idle
                    then:
                      - action: number.set_value
                        metadata: {}
                        data:
                          value: >
                            {% set opt_temp_set =
                            states('input_number.wp_berekende_optimale_temp_set')
                            | int %}

                            {{ opt_temp_set }}
                        target:
                          entity_id: number.adlar_warmtepomp_wp_temp_set
                        enabled: true
                  - action: logbook.log
                    metadata: {}
                    data:
                      entity_id: number.adlar_warmtepomp_wp_temp_set
                      name: Adlar automation
                      message: >-
                        WP Auto Verwarmen: stel in de optimale en de temp set
                        temperatuur: optie 1, temp set of inlet - 1
                  - action: timer.start
                    metadata: {}
                    data:
                      duration: >-
                        00:{{ states('input_number.temperatuurvertraging') | int
                        }}
                    target:
                      entity_id: timer.wachttijd_temp_set_veranderen
                else:
                  - action: logbook.log
                    metadata: {}
                    data:
                      entity_id: number.adlar_warmtepomp_wp_temp_set
                      name: Adlar automation
                      message: >-
                        WP Auto Verwarmen: stel in de optimale en de temp set
                        temperatuur: optie 1, geen actie
      - conditions:
          - condition: trigger
            id:
              - Compressor start
          - condition: state
            entity_id: timer.wachttijd_temp_set_veranderen
            state: idle
          - condition: not
            conditions:
              - condition: state
                entity_id: sensor.kamertemperatuur_waardering
                state: Te koud
        sequence:
          - action: input_number.set_value
            metadata: {}
            data:
              value: >
                {% set temp_set = states('number.adlar_warmtepomp_wp_temp_set')
                | float %}

                {% set inlet_temp =
                states('sensor.adlar_warmtepomp_wp_inlet_temp') | float %}

                {{ [([temp_set - 1, inlet_temp - 1]  | min), 24] |max }}
            target:
              entity_id: input_number.wp_berekende_optimale_temp_set
            enabled: true
          - action: number.set_value
            metadata: {}
            data:
              value: >
                {% set opt_temp_set =
                states('input_number.wp_berekende_optimale_temp_set') | int %}

                {{ opt_temp_set }}
            target:
              entity_id: number.adlar_warmtepomp_wp_temp_set
            enabled: true
          - action: timer.start
            metadata: {}
            data:
              duration: 00:{{ states('input_number.temperatuurvertraging') | int }}
            target:
              entity_id: timer.wachttijd_temp_set_veranderen
          - action: logbook.log
            metadata: {}
            data:
              entity_id: number.adlar_warmtepomp_wp_temp_set
              name: Adlar automation
              message: >-
                WP Auto Verwarmen: stel in de optimale en de temp set
                temperatuur: optie 2, temp set of inlet - 1
mode: single
